---
title: "Tutorial series--Area Comparison"
author:
- name: Bofu Li
  affiliation: "FEC-Water Stewarship Team"
date: "`r Sys.Date()`"
output: distill::distill_article
site: distill::distill_website
description: |
  Area comparison tool tutorials.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Pre-treatment

The Waste Rock (WR) comparison tool can automatically detect the ranges of each waste rock category (e.g., cumulative, yearly, etc.).

## Step 1: Upload the Base- and Application-Case Waste Rock

Upload the Waste Rock input files for the base case and application case.

## Step 2: Select Watershed

Select one of the four watersheds.

## Step 3: Enter Categories

Enter the categories of Waste Rock. Note that users must ensure that the selected categories exist in BOTH Waste Rock input files. If one input file does not contain the selected category, the tool will return an error.

## Step 4: Enter Percentage

The tool uses percentage to determine whether there is a difference between the base case and application case. If the Waste Rock in the application case was zero while the base case values were non-zero, the percentage would be 100%. The percentage equation is as follows:

$$
                 \frac{WR_{Application~base}-WR_{Base~case}}{WR_{Base~case}}
$$

## Step 5: Enter Column Range and Row of RWQM ID

Enter the range of headers in the Waste Rock input file. For example, if the range of headers in the Excel sheet for FRO is A7:AY7, enter "A:AY" for the column range and "7" for the row range.

## Step 6: Process, Download Data, and Visualization

Press the "Process Data" button. After processing the tables, users can download the results as a .CSV file. A new section will appear in the sidebar where users can select one category to visualize the processed data. For cumulative Waste Rock, the tool provides an area plot, while the rest of the plots are lollipop plots.






