---
title: "Tutorial series--flow Comparison"
author:
- name: Bofu Li
  affiliation: "FEC-Water Stewarship Team"
date: "`r Sys.Date()`"
output: distill::distill_article
site: distill::distill_website
description: |
  Flow comparison tool tutorials.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Please edit the flow input before uploading it to the tool. Due to the limited capacity of the server, the tool only supports one realization. If you need a more powerful version, please reach out to me.

## Step 1: Pre-treatment

Keep only one sheet in the flow input files. For example, only keep "R01" in both the base case and application case.

## Step 2: Upload the Base- and Application-Case Flow Input

Upload the flow input files for the base case and application case.

## Step 3: Enter Realization i

If you kept "R01" in the input files, please enter 1. If the value of i is inconsistent with the input file, the tool cannot return the results.

## Step 4: Enter Range of Data

Enter the range of data in both Excel sheets.

## Step 5: Enter Tolerance

Please enter the comparison tolerance.






